### ISSUE TITLE
Fixing potential issue with pychopper.

### ISSUE THREAD

**Issue by keith-harrison** [dbeisser/Natrix2#10]
Hi,
I had the following issue with pychopper:
```
Error in rule pychop:
    jobid: 23
    output: /shared/Natrix2/virexp_results/pychopper/output/kordia_A_R1.fastq, /shared/Natrix2/virexp_results/pychopper/reports/kordia_A_R1.pdf, /shared/Natrix2/virexp_results/pychopper/unclassified/kordia_A_R1.fastq, /shared/Natrix2/virexp_results/pychopper/rescued/kordia_A_R1.fastq
    conda-env: /shared/Natrix2/.snakemake/conda/855e2ab7
    shell:
        
                forward_primer=$(sed -n "2p" /shared/Natrix2/Nanopore_16S.csv | cut -d, -f4);
                reverse_primer=$(sed -n "2p" /shared/Natrix2/Nanopore_16S.csv | cut -d, -f7);
                printf ">SSP
$forward_primer
>VNP
$reverse_primer" > custom_primers.fasta;
                echo "+:SSP,-VNP|-:VNP,-SSP" > config_primers.txt ;
                pychopper -m edlib -b custom_primers.fasta -Q 7  -c config_primers.txt -r /shared/Natrix2/virexp_results/pychopper/reports/kordia_A_R1.pdf -u /shared/Natrix2/virexp_results/pychopper/unclassified/kordia_A_R1.fastq -w /shared/Natrix2/virexp_results/pychopper/rescued/kordia_A_R1.fastq /shared/Natrix2/virexp_data/kordia_A_R1.fastq.gz /shared/Natrix2/virexp_results/pychopper/output/kordia_A_R1.fastq;
                
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
```
To fix this I went to the Conda environment containing the pychopper code causing the problem (was a basic concat error) and changed any dataframe append statements to concat: /shared/Natrix2/.snakemake/conda/855e2ab7/lib/python3.10/site-packages/pychopper/scripts/pychopper.py line 538

```
    # Save stats as TSV:
    stdf = None
    if args.S is not None or args.r is not None:
        stdf = _process_stats(st)
        if tune_df is not None:
            stdf = pd.concat([stdf, pd.DataFrame(tune_df)])
```
Deleting  ~~stdf = stdf.append(pd.DataFrame(tune_df))~~ DELETED

**Comment by DanaBlu** [comment]
Hi @keith-harrison,

Thank you for reporting this issue! We haven't encountered this particular problem before, so I'm curious to investigate further to understand whether it's related to the conda environment or possibly some specific files.

Would it be possible for you to share your Nanopore_16S.csv file and provide a snippet of your kordia_A_R1.fastq file?

Best,
Dana

**Comment by DanaBlu** [comment]
We're glad to get this positive feedback! Since you are working with Nanopore sequences, I recommend you to use the dev branch of Natrix2, if you are not already doing so. It includes Nanopore specific updates and we plan to merge it with the main branch soon!

I wasn't able to reproduce the error with 0 rescued reads. Thus the error is likely related to the conda environment as you suggested. I would recommend removing all existing conda environments along with the corresponding tools before starting Natrix2 for the first time to ensure a clean slate and then restart the pipeline again. 

If you have any further questions or suggestions, please don't hesitate to reach out!
