### ISSUE TITLE
Medaka dependency issue

### ISSUE THREAD

**Issue by theo-krueger** [dbeisser/Natrix2#23]
Hi,

I have been trying to run Natrix2 on the dev branch with Nanopore data with `./pipeline.sh`. During the initial run, at the creation of conda environments, I encountered a package not found error. Medaka 1.1.2 is indeed not available through bioconda for osx-64. There is a gap in available versions between 1.0.3 and 1.8.0. Trying to install 1.8.0 runs into other dependency issues. Trying to run with 1.0.3 is accepted and runs perfectly fine until the medaka step where Natrix exits with an unspecified non-zero exit code in the medaka_polishing rule. 

Do you have an idea of a potential workaround?

Log from initial missing medaka package: [2024-09-05T143442.833687.snakemake.log](https://github.com/user-attachments/files/16894132/2024-09-05T143442.833687.snakemake.log)
Log from error in medaka step: [2024-09-05T150213.857076.snakemake.log](https://github.com/user-attachments/files/16894144/2024-09-05T150213.857076.snakemake.log)

**Comment by dusti1n** [comment]
Hello @theo-krueger,

since you are using osx-64, it is often best to run bioinformatics workflows in a Linux environment to avoid potential compatibility issues. One way to solve your problem is to use Docker to create a container that allows you to run the workflow in a Linux environment. This way, all dependencies, including those that may not be available for osx-64, are properly managed.

Natrix2 has specific version requirements for some packages, and manually changing these requirements can sometimes lead to conflicts. For example, Medaka is often not available for osx-64, which could contribute to the problems you are having.

There will be an official Docker image update for Natrix2 in the next few weeks. In the meantime, you can create your own Docker container. Alternatively, you can also use a Linux virtual machine (VM) to get a fully compatible environment.

If you have access to a workstation or an external server, I recommend using it as it might provide better performance and stability for running these workflows.

If you have any further questions please feel free to contact us.

Best,
Dustin

**Comment by theo-krueger** [comment]
Hello Dustin,
I will try that and I'm looking forward to trying the official relase.
Thanks a lot for your help :)

**Comment by dusti1n** [comment]
> Hello Dustin, I will try that and I'm looking forward to trying the official relase. Thanks a lot for your help :)

Great, I'm glad to hear that.
Have a great day. :)
