### ISSUE TITLE
Error with example data

### ISSUE THREAD

**Issue by gdunshea** [dbeisser/Natrix2#24]
Hi, 

After unsuccessful installation attempts with conda, I managed to install Natrix2 with mamba. There is currently no example data file as indicated in the "Getting started" description. I want to use this for nanopore data and so did try a test run with the Nanopore18S data provided but unfortunately hit this error immediately:

KeyError in line 2 of /data/glennsdata/rotifCOI/MinION/Natrix2/rules/pychop.smk:
'pychopper'
  File "/data/glennsdata/rotifCOI/MinION/Natrix2/Snakefile", line 57, in <module>
  File "/data/glennsdata/rotifCOI/MinION/Natrix2/rules/pychop.smk", line 2, in <module>

Any solutions?

Thanks,
Glenn

**Comment by dusti1n** [comment]
Hi Glenn,

Could you **share** the configuration file you are using to analyze your samples? I’d like to take a look at it. If you haven’t already, could you run a test with our test data (with Nanopore.yaml) to check if the pipeline works correctly?

Please also make sure that the following two parameters in your configuration file are set correctly:

```yaml
dataset:
     nanopore: TRUE

nanopore:
     pychopper: TRUE
```

**It is currently important to use the dev-branch instead of the main-branch.**

If you have any further questions, please feel free to contact us. Have a nice day.

Best regards,
Dustin

**Comment by gdunshea** [comment]
Hi Dustin,

Yes that is what I did - this was with running a test with your data - Nanopore.yaml - in the repo. 

I cannot see:

nanopore:
     pychopper: TRUE

in the Nanopore.yaml however.

Cheers,
Glenn

**Comment by dusti1n** [comment]
**So that I can take a closer look at the problem, please let me know the configuration file you are using so that I can have a look at it.**

The execution of our test data (Nanopore) should not present any problems. I have tested this several times (dev-branch). **Please use the dev-branch not the main-branch**. If you are using the main-branch, the parameter (nanopore: pychopper: TRUE) is not present in the configuration file.

I assume that you have taken the main-branch.

Kind regards,
Dustin

**Comment by gdunshea** [comment]
Ok thanks, I think this can be closed. 
However, can I suggest that you add to the description in your main branch? Or at least to make clear that the dev-branch is currently what should be cloned?

Cheers,
Glenn

**Comment by dusti1n** [comment]
> Ok thanks, I think this can be closed. However, can I suggest that you add to the description in your main branch? Or at least to make clear that the dev-branch is currently what should be cloned?
> 
> Cheers, Glenn

Great! I'm glad we were able to solve your problem. The main branch will be updated with a new version in the next few days, and a new item will be added to the table of contents with information about the dev-branch.

If you have any further questions, feel free to reach out to us.
Have a nice day!

Best regards,
Dustin
